// Kokoro voice list — copied from src/constants.js (id + name only).
export const VOICES = [
    { id: 'af_heart', name: 'Heart (US Female)' },
    { id: 'af_bella', name: 'Bella (US Female)' },
    { id: 'af_alloy', name: 'Alloy (US Female)' },
    { id: 'af_aoede', name: 'Aoede (US Female)' },
    { id: 'af_jessica', name: 'Jessica (US Female)' },
    { id: 'af_kore', name: 'Kore (US Female)' },
    { id: 'af_nicole', name: 'Nicole (US Female)' },
    { id: 'af_nova', name: 'Nova (US Female)' },
    { id: 'af_river', name: 'River (US Male)' },
    { id: 'af_sarah', name: 'Sarah (US Female)' },
    { id: 'af_sky', name: 'Sky (US Female)' },
    { id: 'am_michael', name: 'Michael (US Male)' },
    { id: 'am_adam', name: 'Adam (US Male)' },
    { id: 'am_echo', name: 'Echo (US Male)' },
    { id: 'am_eric', name: 'Eric (US Male)' },
    { id: 'am_fenrir', name: 'Fenrir (US Male)' },
    { id: 'am_liam', name: 'Liam (US Male)' },
    { id: 'am_onyx', name: 'Onyx (US Male)' },
    { id: 'am_puck', name: 'Puck (US Male)' },
    { id: 'bf_emma', name: 'Emma (UK Female)' },
    { id: 'bf_alice', name: 'Alice (UK Female)' },
    { id: 'bf_isabella', name: 'Isabella (UK Female)' },
    { id: 'bf_lily', name: 'Lily (UK Female)' },
    { id: 'bm_daniel', name: 'Daniel (UK Male)' },
    { id: 'bm_fable', name: 'Fable (UK Male)' },
    { id: 'bm_george', name: 'George (UK Male)' },
    { id: 'bm_lewis', name: 'Lewis (UK Male)' },
];

export const DEFAULT_VOICE = 'af_heart';
