"""Server extraction must equal the reader's chunk layout (A1 spec §4). The
expected layouts are generated by the reader's own code (Task 1) — when this
fails, fix server/services/extract.py, never the fixtures."""
import json
import re
from pathlib import Path

import pytest

from server.services import extract
from server.tests.pdfgen import make_pdf

FIXTURES = Path(__file__).parent / "fixtures" / "segmentation"
JS_WS = re.compile(r"[\t\n\v\f\r \xa0\u1680\u2000-\u200a\u2028\u2029\u202f\u205f\u3000\ufeff]")


def _cases():
    return sorted(p for p in FIXTURES.iterdir() if p.suffix in (".txt", ".md"))


@pytest.mark.parametrize("src", _cases(), ids=lambda p: p.name)
def test_layout_matches_reader(src):
    expected = json.loads((FIXTURES / f"{src.name}.expected.json").read_text("utf-8"))
    ftype = "text" if src.suffix == ".txt" else "markdown"
    got = extract.extract_file(src, ftype).chunks
    assert [(c.ord, c.page, c.chunk_type) for c in got] == \
        [(e["ord"], e["page"], e["chunk_type"]) for e in expected]
    for c, e in zip(got, expected):
        if ftype == "text":
            assert c.text == e["text"]
        else:  # markdown text may differ only in whitespace placement
            assert JS_WS.sub("", c.text) == JS_WS.sub("", e["text"])


def test_pdf_one_chunk_per_non_empty_page(tmp_path):
    p = tmp_path / "x.pdf"
    p.write_bytes(make_pdf(["Page one text.", "", "Page three text."]))
    result = extract.extract_pdf(p)
    assert result.page_count == 3
    assert [(c.ord, c.page, c.chunk_type) for c in result.chunks] == [(0, 1, "page"), (1, 3, "page")]
    assert "Page one text." in result.chunks[0].text


def test_pdf_text_never_contains_nul(tmp_path, monkeypatch):
    p = tmp_path / "x.pdf"
    p.write_bytes(make_pdf(["abc"]))
    monkeypatch.setattr(extract, "_pdf_page_texts", lambda path: (["a\x00b."], 1))
    assert extract.extract_pdf(p).chunks[0].text == "ab."


def test_text_page_count_is_reader_page_count():
    result = extract.extract_text("One two three. " * 3)
    assert result.page_count == 1


def test_unknown_type_rejected(tmp_path):
    p = tmp_path / "x.bin"
    p.write_bytes(b"x")
    with pytest.raises(ValueError):
        extract.extract_file(p, "docx")
